coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "src/main/java/fiuba/AlgoChess/Vista"  # ignore folders and all its contents
  - "src/main/java/fiuba/AlgoChess/Controlador"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
